name: CI

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit tests (Jest with coverage)
        run: npm test -- --ci

      - name: Build (Vite)
        run: npm run build

      - name: Cypress run (headless against dev server)
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: 'http://localhost:5173'
          browser: chrome
          config-file: cypress.config.js
          config: baseUrl=http://localhost:5173
        env:
          CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

      # Artifacts are useful for debugging CI failures
      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jest-coverage
          path: coverage

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
